#!/bin/bash
TARGET_DIR="data/games"
INDEX_FILE="$TARGET_DIR/index.js"

mkdir -p "$TARGET_DIR"

# Write header
echo "// auto-generated by scripts/build-game-index.sh" > "$INDEX_FILE"
echo "// do not edit manually" >> "$INDEX_FILE"
echo "" >> "$INDEX_FILE"

# Find all .js files in data/games/ excluding index.js
files=($(ls "$TARGET_DIR"/*.js 2>/dev/null | grep -v "index.js" | sort))

if [ ${#files[@]} -eq 0 ]; then
  echo "export const chunks = [];" >> "$INDEX_FILE"
  echo "Index $INDEX_FILE dibuat (belum ada file game di $TARGET_DIR)."
  exit 0
fi

# Generate imports
index=0
for file in "${files[@]}"; do
  filename=$(basename "$file" .js)
  echo "import * as chunk${index} from './${filename}';" >> "$INDEX_FILE"
  index=$((index+1))
done

echo "" >> "$INDEX_FILE"
echo "export const chunks = [" >> "$INDEX_FILE"

# Generate export array
index=0
for file in "${files[@]}"; do
  echo "  chunk${index}," >> "$INDEX_FILE"
  index=$((index+1))
done

echo "];" >> "$INDEX_FILE"

echo "Berhasil update $INDEX_FILE dengan ${#files[@]} game chunks!"
