#!/bin/bash
OUT="data/games/index.js"
DIR="data/games"
echo "// auto-generated by scripts/build-games-index.sh" > "$OUT"
echo "// do not edit manually" >> "$OUT"
echo "" >> "$OUT"
i=0
for f in "$DIR"/*.js; do
  base=$(basename "$f" .js)
  [ "$base" = "index" ] && continue
  [[ "$base" == _* ]] && continue
  echo "import * as chunk$i from './$base';" >> "$OUT"
  i=$((i+1))
done
echo "" >> "$OUT"
echo "export const chunks = [" >> "$OUT"
for ((j=0; j<i; j++)); do
  echo "  chunk$j," >> "$OUT"
done
echo "];" >> "$OUT"
